repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: flake8

- repo: local
  hooks:

  - id: autoflake
    name: Remove unused variables and imports
    entry: bash -c 'autoflake "$@"; git add -u' --
    language: python
    require_serial: True
    args:
        [
        "--in-place",
        "--remove-all-unused-imports",
        "--remove-unused-variables",
        "--expand-star-imports",
        "--ignore-init-module-imports",
        ]
    files: \.py$

  - id: isort
    name: Sorting import statements
    entry: bash -c 'isort "$@"; git add -u' --
    language: python
    require_serial: True
    args: ["--filter-files"]
    files: \.py$

  - id: black
    name: Black Python code formatting
    entry: bash -c 'black "$@"; git add -u' --
    language: python
    types: [python]
    args: ["--line-length=127"]


  - id: pyDocStyle
    name: PyDocStyle Check
    require_serial: True
    entry: bash -c 'pydocstyle --ignore=D202,D203 -v --match="(?!db).*\.py" --count'
    language: python
    types: [python]
